topics:
  -
    topic: /bridge_msg
    type: std_msgs/msg/String
    queue_size: 10
  -
    topic: /cmd_vel
    type: geometry_msgs/msg/Twist
    queue_size: 10
  -
    topic: /odom
    type: nav_msgs/msg/Odometry
    type_ros1: nav_msgs/Odometry
    type_ros2: nav_msgs/msg/Odometry
    queue_size: 10
    direction: ros1_to_ros2
